sudo: required
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y chromium-chromedriver
install:
  - pip install pytest
  - pip install pytest-html
  - pip install pytest-dotenv
  - pip install selenium
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
services:
  - xvfb
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
script:
  - easyselenium/scripts/easyselenium_cli.py --browser gc .
