sudo: required
dist: trusty
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y chromium-chromedriver
install:
  - pip install pytest
  - pip install pytest-html
  - pip install selenium
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
script:
  - easyselenium/scripts/easyselenium_cli.py -b gc
